export const initialCharacters = [
  {
    id: 'char-david',
    name: 'David',
    role: 'The Shepherd King',
    presentation: 'Masculine',
    age: 'Young adult',
    ethnicity: 'Ancient Levantine',
    skinTone: 'Warm olive',
    hair: 'Dark, short curls',
    clothing: 'Sand linen tunic, rust cloak',
    voice: 'Warm storyteller',
    accent: 'Neutral English',
    language: 'English',
    style: 'Cinematic realism',
    kind: 'man',
    palette: ['#f1bd8e', '#303849', '#d78c57'],
    original: true,
  },
  {
    id: 'char-ada',
    name: 'Ada Okafor',
    role: 'Curious teacher · Lagos',
    presentation: 'Feminine',
    age: 'Early 30s',
    ethnicity: 'Nigerian',
    skinTone: 'Deep brown',
    hair: 'Long box braids',
    clothing: 'Cobalt-blue tailored suit',
    voice: 'Bright, reassuring',
    accent: 'Nigerian English',
    language: 'English',
    style: '3D animation',
    kind: 'woman',
    palette: ['#633a32', '#293a67', '#d98f68'],
    original: true,
  },
  {
    id: 'char-milo',
    name: 'Milo',
    role: 'The Mood Garden explorer',
    presentation: 'Masculine',
    age: 'Child',
    ethnicity: 'Fictional',
    skinTone: 'Light peach',
    hair: 'Soft auburn curls',
    clothing: 'Mint hoodie and yellow trainers',
    voice: 'Playful, curious',
    accent: 'Neutral English',
    language: 'English',
    style: '3D animation',
    kind: 'boy',
    palette: ['#db8f66', '#81b8a5', '#f2c45d'],
    original: true,
  },
  {
    id: 'char-zuri',
    name: 'Zuri',
    role: 'Inventor from the future',
    presentation: 'Feminine',
    age: 'Teen',
    ethnicity: 'Nigerian',
    skinTone: 'Rich umber',
    hair: 'Natural puff, copper cuffs',
    clothing: 'Coral bomber jacket',
    voice: 'Confident, warm',
    accent: 'Nigerian English',
    language: 'English',
    style: '2D animation',
    kind: 'woman',
    palette: ['#55352f', '#e57964', '#dcaa78'],
    original: true,
  },
];

const davidEpisodes = [
  {
    id: 'ep-1',
    title: 'A Shepherd’s Calling',
    status: 'Ready',
    scenes: [
      {
        id: 'sc-1',
        title: 'Morning in the valley',
        description: 'A quiet sunrise washes over the Judean hills as David watches the flock.',
        duration: 7,
        shot: 'Establishing',
        status: 'ready',
      },
      {
        id: 'sc-2',
        title: 'A song in the field',
        description: 'David pauses to play a gentle melody beneath the olive trees.',
        duration: 6,
        shot: 'Medium',
        status: 'ready',
      },
      {
        id: 'sc-3',
        title: 'A call from home',
        description: 'A messenger arrives with news that will change the course of his day.',
        duration: 8,
        shot: 'Close-up',
        status: 'ready',
      },
    ],
  },
  {
    id: 'ep-2',
    title: 'The Anointing',
    status: 'Ready',
    scenes: [
      {
        id: 'sc-4',
        title: 'Samuel arrives',
        description: 'An elder traveler enters the family home looking for the youngest son.',
        duration: 7,
        shot: 'Wide',
        status: 'ready',
      },
      {
        id: 'sc-5',
        title: 'The youngest is chosen',
        description: 'David steps forward, surprised by the quiet attention in the room.',
        duration: 8,
        shot: 'Medium',
        status: 'ready',
      },
      {
        id: 'sc-6',
        title: 'A promise kept close',
        description: 'A gentle moment of hope, held in silence as the family watches.',
        duration: 6,
        shot: 'Close-up',
        status: 'ready',
      },
    ],
  },
  {
    id: 'ep-3',
    title: 'The Giant’s Challenge',
    status: 'In progress',
    scenes: [
      {
        id: 'sc-7',
        title: 'The valley falls silent',
        description: 'Two armies wait on opposite hills beneath a vast, clouded sky.',
        duration: 8,
        shot: 'Establishing',
        status: 'ready',
      },
      {
        id: 'sc-8',
        title: 'A voice across the field',
        description: 'A towering warrior steps into the valley and calls for a champion.',
        duration: 7,
        shot: 'Wide',
        status: 'ready',
      },
      {
        id: 'sc-9',
        title: 'David steps forward',
        description: 'David leaves the safety of the camp, steady and unafraid.',
        duration: 9,
        shot: 'Tracking',
        status: 'draft',
      },
      {
        id: 'sc-10',
        title: 'Five smooth stones',
        description: 'By the stream, David chooses only what he needs for the moment ahead.',
        duration: 6,
        shot: 'Close-up',
        status: 'draft',
      },
      {
        id: 'sc-11',
        title: 'The first step',
        description: 'The young shepherd walks into the open valley as the light breaks through.',
        duration: 8,
        shot: 'Tracking',
        status: 'draft',
      },
    ],
  },
  {
    id: 'ep-4',
    title: 'A Friend in the Palace',
    status: 'Outline',
    scenes: [
      {
        id: 'sc-12',
        title: 'A new home',
        description: 'David arrives at the palace, carrying the memory of the hills with him.',
        duration: 7,
        shot: 'Wide',
        status: 'draft',
      },
      {
        id: 'sc-13',
        title: 'A bond begins',
        description: 'Two young men discover a friendship built on trust and respect.',
        duration: 8,
        shot: 'Medium',
        status: 'draft',
      },
    ],
  },
];

// Sample projects are timestamped relative to the first load so "Edited 2 hours ago" stays accurate.
const HOUR = 60 * 60 * 1000;

export const initialProjects = [
  {
    id: 'project-shepherd',
    title: 'The Shepherd King',
    subtitle: 'A story of courage, calling and an unexpected crown.',
    type: 'Book series',
    style: 'Cinematic realism',
    status: 'In progress',
    image: '/shepherd-king.png',
    updatedAt: Date.now() - 2 * HOUR,
    cast: ['char-david'],
    episodes: davidEpisodes,
  },
  {
    id: 'project-mood-garden',
    title: 'Milo & the Mood Garden',
    subtitle: 'A little story about big feelings.',
    type: 'Animated story',
    style: '3D animation',
    status: 'Ready to export',
    cover: 'garden',
    updatedAt: Date.now() - 26 * HOUR,
    cast: ['char-milo'],
    episodes: [
      {
        id: 'ep-milo-1',
        title: 'The Garden of Feelings',
        status: 'Ready',
        scenes: [
          {
            id: 'mg-1',
            title: 'A very gray morning',
            description: 'Milo wakes to a quiet, cloudy garden and wonders where the colors went.',
            duration: 6,
            shot: 'Wide',
            status: 'ready',
          },
          {
            id: 'mg-2',
            title: 'Meet the little feelings',
            description: 'Friendly little characters introduce themselves among the garden beds.',
            duration: 7,
            shot: 'Medium',
            status: 'ready',
          },
          {
            id: 'mg-3',
            title: 'A color returns',
            description: 'Milo names what he is feeling, and one tiny flower opens.',
            duration: 8,
            shot: 'Close-up',
            status: 'ready',
          },
        ],
      },
    ],
  },
  {
    id: 'project-fractions',
    title: 'Fractions made simple',
    subtitle: 'A visual lesson for curious learners.',
    type: 'Education',
    style: '2D animation',
    status: 'Draft',
    cover: 'fractions',
    updatedAt: Date.now() - 8 * 24 * HOUR,
    cast: ['char-ada'],
    episodes: [
      {
        id: 'ep-frac-1',
        title: 'Comparing fractions',
        status: 'Draft',
        scenes: [
          {
            id: 'fr-1',
            title: 'Pizza makes a point',
            description: 'Ada introduces fractions with a colourful, familiar classroom example.',
            duration: 7,
            shot: 'Wide',
            status: 'draft',
          },
          {
            id: 'fr-2',
            title: 'Same-size pieces',
            description: 'Two circles reveal how equal parts make a fair comparison.',
            duration: 8,
            shot: 'Medium',
            status: 'draft',
          },
          {
            id: 'fr-3',
            title: 'Which is bigger?',
            description: 'Learners make a quick prediction before the answer appears.',
            duration: 6,
            shot: 'Close-up',
            status: 'draft',
          },
        ],
      },
    ],
  },
];

export const sampleChapters = [
  {
    id: 'sample-1',
    title: 'A Shepherd’s Calling',
    excerpt:
      'In a quiet valley, a young shepherd learns to care for his flock and finds courage in the small things he does each day.',
    selected: true,
    words: 740,
  },
  {
    id: 'sample-2',
    title: 'The Anointing',
    excerpt:
      'A traveler arrives at the family home. The youngest son is called in from the fields, and an unexpected promise begins.',
    selected: true,
    words: 980,
  },
  {
    id: 'sample-3',
    title: 'The Giant’s Challenge',
    excerpt:
      'Two armies face one another across a valley. David arrives with food for his brothers and hears a challenge no one will answer.',
    selected: true,
    words: 1120,
  },
  {
    id: 'sample-4',
    title: 'A Friend in the Palace',
    excerpt:
      'David enters a new world at the palace and finds an unlikely friend whose loyalty will change them both.',
    selected: true,
    words: 880,
  },
  {
    id: 'sample-5',
    title: 'The Long Road Home',
    excerpt:
      'As life grows complicated, David leaves the palace and learns that courage can also mean knowing when to wait.',
    selected: false,
    words: 1030,
  },
];
